---
name: Deploy Supabase + Vercel

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Supabase CLI
        run: |
          curl -L https://github.com/supabase/cli/releases/download/v2.39.2/supabase_linux_amd64.tar.gz -o supabase.tar.gz
          mkdir supabase-cli
          tar -xzf supabase.tar.gz -C supabase-cli
          sudo mv supabase-cli/supabase /usr/local/bin/supabase
          rm -rf supabase-cli supabase.tar.gz

      - name: Link to Supabase
        run: |
          supabase link --project-ref etfhkltquzhysvmhbkfg --password $SUPABASE_DB_PASSWORD
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Push database migrations
        run: supabase db push
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
